apiVersion: v1
kind: Secret
metadata:
  name: nodejs-secret
type: Opaque
stringData:
  DB_HOST: "mysql"
  DB_USER: "root"
  DB_PASSWORD: "supersecretpassword"
  DB_NAME: "ivolve"
  API_KEY: "my-secret-api-key"
