@Library('my-shared-library') _

pipeline {
    agent { label 'agent-1' }

    environment {
        DOCKER_IMAGE = "rawdaessamrou/jenkins-app:${env.BUILD_ID}"
        DOCKER_CREDENTIALS_ID = 'docker-credentials'
    }

    stages {
        stage('Clone Source') {
            steps { checkout scm }
        }
        stage('RunUnitTest') {
            steps { runUnitTest() }
        }
        stage('BuildApp') {
            steps { buildApp() }
        }
        stage('BuildImage') {
            steps { buildImage(env.DOCKER_IMAGE) }
        }
        stage('ScanImage') {
            steps { scanImage(env.DOCKER_IMAGE) }
        }
        stage('PushImage') {
            steps { pushImage(env.DOCKER_IMAGE, DOCKER_CREDENTIALS_ID) }
        }
        stage('RemoveImageLocally') {
            steps { removeImageLocally(env.DOCKER_IMAGE) }
        }
        stage('DeployOnK8s') {
            steps { deployOnK8s() }
        }
    }
    post { always { cleanWs() } }
}
