@Library('my-shared-library') _

pipeline {
    agent { label 'agent-1' }

    environment {
        DOCKER_IMAGE = "rawdaessamrou/jenkins-app:${env.BUILD_ID}"
        DOCKER_CREDENTIALS_ID = 'docker-credentials'
    }

    stages {
        stage('Clone Source') {
            steps { checkout scm }
        }
        stage('Build & Test') {
            steps { buildAndTest() }
        }
        stage('Image: Build → Scan → Push → Cleanup') {
            steps { imageLifecycle(env.DOCKER_IMAGE, DOCKER_CREDENTIALS_ID) }
        }
        stage('Deploy on K8s') {
            steps { deployOnK8s() }
        }
    }
    post { always { cleanWs() } }
}
