pipeline {
    agent any

    environment {
        DOCKER_IMAGE  = "rawdaessamrou/jenkins-app"
        IMAGE_TAG     = "${BUILD_NUMBER}"
        APP_DIR       = "GitOps Workflow with ArgoCD/Lab 24 - GitOps workflow/Jenkins_App"
        MANIFEST_PATH = "GitOps Workflow with ArgoCD/Lab 24 - GitOps workflow"
    }

    stages {

        stage('Build App') {
            steps {
                dir("${APP_DIR}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh "docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-credentials',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh "docker push ${DOCKER_IMAGE}:${IMAGE_TAG}"
                }
            }
        }

        stage('Delete Image Locally') {
            steps {
                sh "docker rmi ${DOCKER_IMAGE}:${IMAGE_TAG}"
            }
        }

        stage('Update deployment.yaml') {
            steps {
                withCredentials([string(credentialsId: 'github-credintials', variable: 'GH_TOKEN')]) {
                    sh """
                        git clone https://\${GH_TOKEN}@github.com/rawdaessamrou/iVolve-Tasks.git manifest-repo
                        cd "manifest-repo/${MANIFEST_PATH}"
                        sed -i 's|image: ${DOCKER_IMAGE}:.*|image: ${DOCKER_IMAGE}:${IMAGE_TAG}|g' deployment.yaml
                    """
                }
            }
        }

        stage('Push Updated Manifest to GitHub') {
            steps {
                withCredentials([string(credentialsId: 'github-credintials', variable: 'GH_TOKEN')]) {
                    sh """
                        cd manifest-repo
                        git config user.email "ci@jenkins.local"
                        git config user.name "Jenkins CI"
                        git add "${MANIFEST_PATH}/deployment.yaml"
                        git commit -m "ci: update image to ${DOCKER_IMAGE}:${IMAGE_TAG}"
                        git push https://\${GH_TOKEN}@github.com/rawdaessamrou/iVolve-Tasks.git main
                    """
                }
            }
        }
    }

    post {
        always { cleanWs() }
    }
}
